# Generated by Django 6.0.3 on 2026-04-06 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial_Record',
                'verbose_name_plural': 'Financial_Records',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
